### ISSUE TITLE
DDS configuration for the project

### ISSUE THREAD

**Issue by LanderU** [ros2-realtime-demo/pendulum#10]
> HI, I was also thinking to test different DDS and QoS settings with the real time demo. Any documentation on how to change the DDS by command line or will I have to change the source code?

Originally posted here:https://github.com/ros2-realtime-demo/pendulum/issues/5#issuecomment-565398413, by: @Viplav04

**Comment by LanderU** [comment]
> The DDS configuration from ROS 2 is quite limited (See this for example). At this point they way you have to configure each DDS is by setting the QoS profile configuration file. The configuration parameters depends on each DDS implementation so you will need to take a look to the documentation to tune them. Here you have some links that may help you:
FastRTPS: https://roscon.ros.org/2017/presentations/ROSCon%202017%20ROS2%20Fine%20Tuning.pdf, https://fast-rtps.docs.eprosima.com/en/latest/xmlprofiles.html
RTI Connext pro: https://research.rti.com/rti-doc/500/ndds.5.0.0/doc/html/api_cpp/index.html
Opensplice: http://download.ist.adlinktech.com/docs/Vortex/html/ospl/ConfGuide/index.html
Cyclone: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/config.rst, https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md
...
You probably want to take a took configuration parameters relevant to real-time such as thread priorities, memory locking, etc.
In any case I think this topic deviates from the main topic of this issue. I suggest you to open a new issue and continue the discussion in that one.

Answered by @carlossvg on: https://github.com/ros2-realtime-demo/pendulum/issues/5#issuecomment-565578692

**Comment by carlossvg** [comment]
Closing in favor of https://real-time-working-group.readthedocs.io/en/latest/Guides/Configure-RMW-Implementation/configure_rmw.html
