### ISSUE TITLE
ROS 2 Eloquent Elusor

### ISSUE THREAD

**Issue by carlossvg** [ros2-realtime-demo/pendulum#12]
This issue will track the status of the pendulum demo improvements introduced for ROS 2 Eloquent Elusor.

- Add support for ROS tracing tools #9
- Create integration test using [launch_testing](https://github.com/ros2/launch/tree/master/launch_testing)
- Improve code to follow real-time programming guidelines #11
- Make the demo easier to use
   * Add an "auto-init" option to make all the nodes go to active state without the pendulum manager. 
   * Add support for ADE (https://ade-cli.readthedocs.io/en/latest/)
   * Launch everything with one command (see for example https://ubuntu.com/blog/building-a-better-turtlebot3)
   * Add scripts to teleoperate the pendulum in a loop. 
- Allow the user to select differen QoS policies from command line.
- Allow the user to select different scheduling policies (i.e: [SCHED_DEADLINE](https://en.wikipedia.org/wiki/SCHED_DEADLINE))
- Avoid repeated code in `pendulum_demo` executables. Most code in standalone and composition executables for cli options is repeated.

**Comment by LanderU** [comment]
@carlossvg I think we can close this issue. Some of the features are covered on foxy branch. Or shall we keep this open and backport the new features onto eloquent?

**Comment by carlossvg** [comment]
@LanderU I would just close this issue for the moment since most updates are only relevant for foxy.
