### ISSUE TITLE
Unable to build workspace

### ISSUE THREAD

**Issue by pep248** [ros2-realtime-demo/pendulum#25]
```bash
fatal error: sensor_msgs/msg/joint_state.hpp: No such file or directory
 #include "sensor_msgs/msg/joint_state.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pendulum_controller_node.dir/src/pendulum_controller_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/pendulum_controller_node.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< pendulum_controller_node [0.15s, exited with code 2]
Aborted  <<< pendulum_driver [0.14s]
```

**Comment by LanderU** [comment]
Hey @pep248, thanks for trying it out. It's a bit complicated to help you without more information. Could you please add here more context?

* Which branch are you building?
* Which ROS2 version do you have installed in your system?

**Comment by carlossvg** [comment]
@LanderU I would suggest we add some notes to the instructions explaining that it is necessary to source the workspace. We can do that once we finish with the foxy integration and the ADE image. Apart from that, I would close this issue if no more information is provided.

**Comment by LanderU** [comment]
@carlossvg sure, we need to improve our docs. I'll keep this open until Monday 08/10, if no more activity I'll close it.
