### ISSUE TITLE
[Foxy] Add ros_tracing support in ADE

### ISSUE THREAD

**Issue by carlossvg** [ros2-realtime-demo/pendulum#36]
- [x] Install lttng and other required tools
- [x] Create docker image with ros foxy built with traces enabled (if required)
- [x] Add configuration for kernel tracing: https://lttng.org/docs/v2.10/#doc-tracing-group
   - `[ERROR] [launch]: Caught exception in launch (see debug for traceback): channel enabling failed: Tracing the kernel requires a root lttng-sessiond daemon, as well as "tracing" group membership or root user ID for the lttng client.`
- [x] Consider if it is necessary to create a specific directory to store trace sessions. The default is `$USER/.ros/tracing/`.

**Comment by LanderU** [comment]
Regarding to point 3 in my case:

```bash
lander@ade:~$ lttng-sessiond --daemonize
lander@ade:~$ 
```

**Comment by carlossvg** [comment]
Done in:
- https://github.com/ros2-realtime-demo/pendulum/pull/42
- https://github.com/ros2-realtime-demo/pendulum/pull/39
