### ISSUE TITLE
Process dies when using lifecycle transitions

### ISSUE THREAD

**Issue by carlossvg** [ros2-realtime-demo/pendulum#47]
**Describe the bug**

When the nodes are transitioned using the command line lifecycle utils the process dies unexpectedly. This doesn't happen when the nodes are transitioned automatically using `autostart`.

The issues seem to be related to an incompatible QoS generated by the deadline QoS usage. If this QoS is removed, it works as expected. 

- Exception thrown: https://github.com/ros2/rclcpp/blob/foxy/rclcpp/include/rclcpp/qos_event.hpp#L124
- When the joint_states subscription is created:  https://github.com/ros2/rclcpp/blob/foxy/rclcpp/include/rclcpp/create_subscription.hpp#L145
- "Provided event_type is not supported by rmw_fastrtps_cpp"

**To Reproduce**

Terminal 1:
```bash
ros2 launch pendulum_bringup pendulum_bringup.launch.py autostart:=False
```
Terminal 2:
```bash
ros2 lifecycle set /pendulum_controller configure
```

Terminal 1:
```bash
[ERROR] [pendulum_demo-1]: process has died [pid 182186, exit code -11, cmd '/home/odin/adehome/pendulum_ws/install/pendulum_demo/lib/pendulum_demo/pendulum_demo --autostart False --priority 0 --cpu-affinity 0 --lock-memory False --lock-memory-size 0 --config-child-threads False --ros-args --params-file /home/odin/adehome/pendulum_ws/install/pendulum_bringup/share/pendulum_bringup/params/pendulum.param.yaml'].
```

**Expected behavior**

It is possible to use `ros2 lifecycle` to activate the nodes successfully.  

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 
**Additional context**

**Comment by LanderU** [comment]
Solved via: https://github.com/ros2-realtime-demo/pendulum/pull/48
