### ISSUE TITLE
Real time testing : no topic /controller_statistics

### ISSUE THREAD

**Issue by Viplav04** [ros2-realtime-demo/pendulum#6]
Hello,
I am trying the real time testing for this demo.

After running : 
```ros2 run pendulum_demo pendulum_demo --pub-stats```

I cannot see /controller_statistics topic. I followed all the steps listed in that demo. What can be wrong here? 

I only get these topics : 
~$ ```ros2 topic list```
/parameter_events
/pendulum_controller/transition_event
/pendulum_driver/transition_event
/rosout

**Comment by Viplav04** [comment]
Another terminal has to launch 
```ros2 run pendulum_manager pendulum_manager```
then it works. Please update real time instructions

**Comment by LanderU** [comment]
Thanks for the catch!
