### ISSUE TITLE
Real Time testing - server time out

### ISSUE THREAD

**Issue by Viplav04** [ros2-realtime-demo/pendulum#8]
**Describe the bug**
```bash
[ERROR] [pendulum_controller]: Server time out while getting current state for node 0��IrU
[ERROR] [pendulum_driver]: Server time out while getting current state for node 
[ERROR] [pendulum_controller]: Server time out while getting current state for node `��IrU
[ERROR] [pendulum_driver]: Server time out while getting current state for node 
```

**To Reproduce**
```bash
ros2 run pendulum_demo pendulum_demo  --pub-stats --lock-memory
```

ros2 run pendulum_manager pendulum_manager
and activate all nodes

**Expected behavior**
Cannot see ros2 topic echo /controller_statistics

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04, rt-4.13.103 patch
ROS2 dashing
memory locked 100MB

How did you run it? Am I missing something?

Also when I try 
```bash
pendulum_ws# ros2 run pendulum_demo pendulum_demo --pubstats --priority 80 --lock-memory-size 50000
proc rt init mem aligning failedCannot allocate memory
terminate called after throwing an instance of 'std::runtime_error'
  what():  proc rt init mem aligning failed
```

**Comment by LanderU** [comment]
Thanks for reporting! Not sure if I'll be available to test it in some weeks.

**Comment by Viplav04** [comment]
Can you guide me a bit ? What can be the problems for this? I am installing a new Linux RT kernel and will test it again

**Comment by LanderU** [comment]
Hmm, not sure, looks like a permissions issue. But, I need to have a look deeply.

**Comment by Viplav04** [comment]
During boot-up of real-time kernel, EFI memmap is not enabled. I think this is the problem. But I can't find good information on how to fix it.

**Comment by Viplav04** [comment]
Hello @LanderU  Can you help me with this? When I run as root I have memory lock and real time priority set, but the pendulum_demo node kills itself when run with memory lock.

**Comment by LanderU** [comment]
@Viplav04, could you please share a bit more about your setup. How are you installing preempt-rt kernel, what is your platform? What is your preempt-rt configuration?

**Comment by LanderU** [comment]
Also, it would be great if you post here how are you running the project.

**Comment by Viplav04** [comment]
Hey @LanderU 
I follow this script.
echo "Get Kernel Source"

wget https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.4.3.tar.xz

echo "Get Kernel Patch"

wget https://www.kernel.org/pub/linux/kernel/projects/rt/5.4/patch-5.4.3-rt1.patch.xz

echo "Unpack Kernel Source"
xz -cd linux-5.4.3.tar.xz | tar xvf -

cd linux-5.4.3/

echo "Patching Kernel"

xzcat ../patch-5.4.3-rt1.patch.xz | patch -p1

echo "Install dependencies"

sudo apt-get install libncurses-dev
sudo apt-get install libssl-dev

cp /boot/config-$(uname -r) .config

echo "Make Menuconfig"

echo "Please Navigate to 'Processor type and features' ---> 'Preemption Model'"

echo "and choose 'Fully Preemptible Kernel'" 

make menuconfig

#####

make -j20

sudo make modules_install -j20
sudo make install -j20

sudo update-grub

#sudo reboot

After this, I sign the kernel according to this link:
https://askubuntu.com/questions/1081472/vmlinuz-4-18-12-041812-generic-has-invalid-signature

When I run as root, it has real-time settings but the node kills itself within a few seconds if i do --lock-memory
and with --lock-memory-size, it says proc rt init mem aligning failedCannot allocate memory as mentioned above in the 1st comment.

I am not sure what is the issue, but I found during bootup, efi_memmap is not enabled

**Comment by LanderU** [comment]
Okay, I'm going to patch a computer with exactly your same kernel version to see what's happen. I'll back to you.

**Comment by LanderU** [comment]
Here my results:

https://asciinema.org/a/jD1zTaoHxUi48hDC2ksxlUyQt

**Comment by LanderU** [comment]
Without root:

```bash
lander@lander-pc:/tmp/pendulum_ws$ ros2 run pendulum_demo pendulum_demo --priority 80
Couldn't set scheduling priority and policy: Operation not permitted
^C[INFO] [rclcpp]: signal_handler(signal_value=2)
lander@alias:/tmp/pendulum_ws$ ros2 run pendulum_demo pendulum_demo --lock-memory-size 1000
mlockall failed: Cannot allocate memory
Couldn't lock  virtual memory.
^C[INFO] [rclcpp]: signal_handler(signal_value=2)
```

**Comment by Viplav04** [comment]
Thank you, I was using 50 MB and maybe that's why it was failing.

**Comment by Reubenyuhe** [comment]
I've got the same issue as you do. I have also tried run it as `root` with a lower locked Memory. But it came out with the same result. 

```
root@raspberrypi:~# ros2 run pendulum_demo pendulum_demo --lock-memory-size 5000 --pub-stats 
proc rt init mem aligning failedCannot allocate memory
terminate called after throwing an instance of 'std::runtime_error'
what():  proc rt init mem aligning failed
```
Meanwhile it seem to work without --lock-memory-size or --lock-memory 

```
root@raspberrypi:~# ros2 run pendulum_demo pendulum_demo
[INFO] [1595155656.627427496] [pendulum_controller]: on_configure() is called.
[INFO] [1595155656.749415646] [pendulum_driver]: on_configure() is called.
[INFO] [1595155656.772185046] [pendulum_controller]: on_activate() is called.
[INFO] [1595155656.783296932] [pendulum_driver]: on_activate() is called.
```

How did you fix it ? @Viplav04  
 
Here is my configuration:
Hardware: Raspberry Pi 3B+
OS: Raspbian GNU/Linux 10 (buster) 
Kernel-RT-patch: 4.19.71-rt24-v7+
Distro: ROS 2 foxy build from source 
RMW: RTI connext DDS 5.3.1

**Comment by Viplav04** [comment]
Try with 1000 size, worked for me

Kind regards
Viplav

**Comment by LanderU** [comment]
@Reubenyuhe we're on the process of refactoring the code. Also, the project has not been tested under Foxy. We're working to add support for it and also, we'll generate some guidelines to run the project under x86 and aarch64 and armv7 (with RT settings).

**Comment by Reubenyuhe** [comment]
@Viplav04 It still didn't work for me. But right now I can live with that. Thanks a lot.
