### ISSUE TITLE
rt_thread include vs src function declaration discrepancy

### ISSUE THREAD

**Issue by adrianbattiston** [ros2-realtime-demo/pendulum#83]
pendulum_utils/include/pendulum_utils/rt_thread.hpp declares set_thread_priority() and set_thread_cpu_affinity() with 2 and 1 input variables respectively, 

pendulum_utils/src/rt_thread.cpp specifies them with 3 and 2 input variables respectively:

hpp: int set_thread_priority(size_t sched_priority, int policy);
cpp: int set_thread_priority(pid_t pid, size_t sched_priority, int policy)

hpp: int set_thread_cpu_affinity(uint32_t cpu_bit_mask);
cpp: int set_thread_cpu_affinity(pid_t pid, uint32_t cpu_bit_mask)

When these functions are used in files outside this specific node the compiler throws "too many arguments to function" errors as it only checks the header file at compile time.  There's no issues using set_this_thread_cpu_affinity() or set_this_thread_priority(). 

Not sure if this is an intended structure?

**Comment by carlossvg** [comment]
@adrianbattiston Yes, this is a bug. I will fix this. Thanks for reporting!
